### ISSUE TITLE
cool

### ISSUE THREAD

**Issue by vnt-dev** [asakhar/wtun#1]
Is this a rust implementation of wintun? It’s really cool ! I am planning to implement it

**Comment by vnt-dev** [comment]
Can I include it in my project

**Comment by asakhar** [comment]
sure you can. i didn't bother with licence stuff for now, but i am going to refer to wintun's original licence. Keep in mind that only userspace code has been rewritten in rust. Kernel driver is still written in C and I used the original driver files from wintun to keep the driver signature.

**Comment by vnt-dev** [comment]
very good. I have already started using it. If I remove the ring buffer, will the read and write speed be faster? I want to create external buffering to avoid memory duplication. Do you think it's feasible? Additionally, I admire you so much for being able to write 'wtun'
